[package]
name = "hugin-influx"
version.workspace = true
edition.workspace = true

[dependencies]
hugin-core = { path = "../hugin-core" }
tokio = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

[dev-dependencies]
wiremock = "0.6"
tokio = { workspace = true }

