[package]
name = "huginn-probes"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
huginn-core = { path = "../huginn-core", version = "0.1.0" }
tokio = { workspace = true }
reqwest = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
tracing = { workspace = true }
chrono = { workspace = true }
hickory-resolver = { workspace = true }

[dev-dependencies]
wiremock = "0.6"
