[package]
name = "hugin-web"
version.workspace = true
edition.workspace = true

[dependencies]
hugin-core = { path = "../hugin-core" }
axum = { workspace = true }
tokio = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
anyhow = { workspace = true }
tokio-stream = { workspace = true }
